services:
  frontend:
    build: ./src/frontend
    ports:
      - "8000:5173"
    volumes:
      - ./src/frontend:/app:z
    command: yarn dev --host 0.0.0.0
  backend:
    build: ./src/backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=;http://*:80
    ports:
      - "5000:80"
    command: ["dotnet", "watch","run", "--project" , "hilfreichAPI.csproj", "--urls", "http://*:80"]
    volumes:
      - ./src/backend/hilfreichAPI:/app:z
      - /app/obj/ # <- directory won't be mounted
      - /app/bin/ # <- directory won't be mounted
      - /app/hilfreichAPI/obj/ # <- directory won't be mounted
      - /app/hilfreichAPI/bin/ # <- directory won't be mounted
      - ~/.aspnet/https:/https:ro
