services:
  frontend:
    build: ./src/frontend
    ports:
      - "8000:5173"
    volumes:
      - ./src/frontend:/app:z
    command: yarn dev --host 0.0.0.0
  backend:
    build: ./src/backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=;http://*:80
    ports:
      - "5000:80"
    command: ["dotnet", "watch","run", "--project" , "hilfreichAPI.csproj", "--urls", "http://*:80"]
    volumes:
      - ./src/backend/hilfreichAPI:/app:z
      - /app/obj/ # <- directory won't be mounted
      - /app/bin/ # <- directory won't be mounted
      - /app/hilfreichAPI/obj/ # <- directory won't be mounted
      - /app/hilfreichAPI/bin/ # <- directory won't be mounted
      - ~/.aspnet/https:/https:ro

  db:
    image: postgres
    restart: always
    ports:
    - "5432:5432"
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example
